empfaenger.c File Reference
#include `sharedmemory.h`
Functions
int main (int argc, char *argv[])
empfaenger
Detailed Description
sharedmemory Beispiel 3
Author
Karin Kalman <karin.kalman@technikum-wien.at>
Michael Mueller <michael.mueller@technikum-wien.at>
Gerhard Sabeditsch <gerhard.sabeditsch@technikum-wien.at>
Date
2016/05/28
Version
Revision
1
URL: $HeadURL$
Last Modified: Author
Gerhard
Definition in file empfaenger.c.
Function Documentation
int main (int argc, char * argv[])
Empfaenger Programm
A empfaenger receives data from a shared memory
Parameters
argc the number of arguments
argv the arguments itselves (including the program name in argv[0])
Returns
0 or -1
Return values
0 (Everything OK)
-1 (Something goes wrong)
Definition at line 47 of file empfaenger.c.
References closeSegment(), createSegment(), parseParameter(), READ_MODE, data_collect::segment, data_collect::sem_r, data_collect::sem_w, and data_collect::shm_size.