sender.c File Reference
#include `sharedmemory.h`
Functions
int main (int argc, char *argv[])
sender
Detailed Description
sharedmemory Beispiel 3
Author
Karin Kalman <karin.kalman@technikum-wien.at>
Michael Mueller <michael.mueller@technikum-wien.at>
Gerhard Sabeditsch <gerhard.sabeditsch@technikum-wien.at>
Date
2016/04/17
Version
Revision
1
URL: $HeadURL$
Last Modified: Author
Gerhard
Definition in file sender.c.
Function Documentation
int main (int argc, char * argv[])
Sender Programm
A sender transmitts data to a shared memory
Parameters
argc the number of arguments
argv the arguments itselves (including the program name in argv[0])
Returns
0 or -1
Return values
0 (Everything OK)
-1 (Something goes wrong)
Definition at line 47 of file sender.c.
References closeSegment(), createSegment(), parseParameter(), data_collect::segment, data_collect::sem_r, data_collect::sem_w, data_collect::shm_size, and WRITE_MODE.