sharedmemory.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include <sys/types.h>
#include <unistd.h>
#include <sem182.h>
#include <signal.h>
Classes
struct data_collect
Defines
#define SHM_KEY getuid() * 1000 + 0
#define SEM_R_KEY getuid() * 1000 + 1
#define SEM_W_KEY getuid() * 1000 + 2
#define READ_MODE 0
#define WRITE_MODE 1
Functions
data_collect createSegment (int shm_size, int shm_mode)
createSegment
int closeSegment (data_collect shm_sem)
closeSegment
int parseParameter (int argc, char *argv[])
parseParameter
Detailed Description
sharedmemory Beispiel 3
Author
Karin Kalman <karin.kalman@technikum-wien.at>
Michael Mueller <michael.mueller@technikum-wien.at>
Gerhard Sabeditsch <gerhard.sabeditsch@technikum-wien.at>
Date
2016/05/28
Version
Revision
1
URL: $HeadURL$
Last Modified: Author
Gerhard
Definition in file sharedmemory.h.
Define Documentation
#define READ_MODE 0
Definition at line 48 of file sharedmemory.h.
Referenced by createSegment(), and main().
#define SEM_R_KEY getuid() * 1000 + 1
Definition at line 45 of file sharedmemory.h.
Referenced by createSegment().
#define SEM_W_KEY getuid() * 1000 + 2
Definition at line 46 of file sharedmemory.h.
Referenced by createSegment().
#define SHM_KEY getuid() * 1000 + 0
Definition at line 44 of file sharedmemory.h.
Referenced by createSegment().
#define WRITE_MODE 1
Definition at line 49 of file sharedmemory.h.
Referenced by main().
Function Documentation
int closeSegment (data_collect shm_sem)
closeSegment
cleans up semaphores, detatches shared memory segment and mark as removeable
Parameters
shm_sem
Returns
> -1 or -1
Return values
> -1 ==> Everything OK
-1 ==> Somthing goes wrong
Definition at line 140 of file sharedfunctions.c.
References data_collect::segment, data_collect::sem_r, data_collect::sem_w, and data_collect::shmid.
Referenced by createSegment(), and main().
data_collect createSegment (int shm_size, int shm_mode)
createSegment
creates a a ring buffer and there semaphores
Parameters
shm_size size of the ring buffer
shm_mode (read or write)
Returns
NULL or ! NULL
Return values
! NULL ==> Everything OK
NULL ==> Somthing goes wrong
Definition at line 50 of file sharedfunctions.c.
References closeSegment(), READ_MODE, data_collect::segment, data_collect::sem_r, SEM_R_KEY, data_collect::sem_w, SEM_W_KEY, SHM_KEY, data_collect::shm_size, data_collect::shmid, and data_collect::use_mode.
Referenced by main().
int parseParameter (int argc, char * argv[])
parseParameter
get the size of the ringbuffer out of the given parameters
Returns
>0 or -1
Return values
>0 ==> Everything OK
-1 ==> Somthing goes wrong
Definition at line 201 of file sharedfunctions.c.
Referenced by main().